import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/nav-bar";
import QueryClientProvider from "@/app/utils/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <NavBar />
          <main className="container mx-auto px-4 max-w-6xl">{children}</main>
        </QueryClientProvider>
      </body>
    </html>
  );
}
